[phases.setup]
nixPkgs = ['python311', 'uv']

[phases.install]
cmds = [
  'pip install uv==0.4.30',
  'uv sync --no-dev --frozen'
]

[phases.start]
cmds = ['python main.py']  # Change this to your actual entry point
