[phases.setup]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install uv==0.4.30"
]

[phases.install]
cmds = [
  "/opt/venv/bin/uv sync --no-dev --frozen"
]

[start]
cmd = "/opt/venv/bin/python main.py"
