name: ðŸ› Bug Report
description: Report a bug or issue in the ACI backend API, dev portal, or SDK.
title: "[Your Bug Report Title Here]"
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Please make sure the issue is clear, reproducible, and easy to act on. (Feel free to ask in [Discussions](https://github.com/aipotheosis-labs/aci/discussions) first if unsure)

  - type: checkboxes
    id: pre-requisites
    attributes:
      label: "Required Pre-requisites"
      description: "Please make sure you've completed the following steps before submitting. Thank you! ðŸ™"
      options:
        - label: "I have read the [Documentation](https://www.aci.dev/docs)"
          required: true
        - label: "I have searched the [Issue Tracker](https://github.com/aipotheosis-labs/aci/issues) and [Discussions](https://github.com/aipotheosis-labs/aci/discussions) that this hasn't been reported yet."
          required: true
        - label: "Consider asking in [Discussions](https://github.com/aipotheosis-labs/aci/discussions) first"
          required: false

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please provide a clear and concise description of the bug or issue, the expected behavior, the actual behavior, and steps to reproduce the issue. Thank you! ðŸ™"
      placeholder: |
        Description:

        Expected behavior:

        Actual behavior:

        Steps to reproduce:

    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: >-
        Add any other context about the problem here. Screenshots, logs, etc may also be helpful.

        If you know or suspect the reason for this bug, paste the code lines and suggest modifications.
    validations:
      required: false
