name: 💡 Feature Request
description: Request a new feature or enhancement in the ACI backend API, dev portal, or SDK.
title: "[Your Feature Request Title Here]"
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Please make sure the feature request is clear, reproducible, and easy to act on. (Feel free to ask in [Discussions](https://github.com/aipotheosis-labs/aci/discussions) first if unsure)

  - type: checkboxes
    id: pre-requisites
    attributes:
      label: "Required Pre-requisites"
      description: "Please make sure you've completed the following steps before submitting. Thank you!"
      options:
        - label: "I have read the [Documentation](https://www.aci.dev/docs)"
          required: true
        - label: "I have searched the [Issue Tracker](https://github.com/aipotheosis-labs/aci/issues) and [Discussions](https://github.com/aipotheosis-labs/aci/discussions) that this hasn't been reported yet."
          required: true
        - label: "Consider asking in [Discussions](https://github.com/aipotheosis-labs/aci/discussions) first"
          required: false

  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Please provide a clear and concise description of the feature request, the motivation for the feature, and any additional context that would be helpful. Thank you! 🙏"
      placeholder: |
        Motivation:

        Additional context:

    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: "Proposed Solution"
      description: "Please provide a description of the proposed solution."
      placeholder: |
        Proposed solution:

        Additional context:

    validations:
      required: true
