name: Dev Portal Checks

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]
  schedule:
    - cron: "0 9 * * *"

jobs:
  ci:
    name: Format, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci --legacy-peer-deps

      - name: Check formatting
        working-directory: frontend
        run: npm run format:check

      - name: Run linter
        working-directory: frontend
        run: npm run lint

      - name: Run tests
        working-directory: frontend
        run: npm run test

      - name: Build
        working-directory: frontend
        env:
          NEXT_PUBLIC_AUTH_URL: https://8367878.propelauthtest.com
        run: npm run build
